services:

    rest_api_test.request_access_checker:
        class: Litvinab\Bundle\RestApiTestBundle\Service\RequestAccessChecker
        arguments:
          - "%rest_api_test.controller_on%"
          - "%rest_api_test.access_token%"